[tox]
envlist = py38, py39, py310, py311, py312, py313

[testenv]
deps =
    pytest
    munch
    kitchen
    requests
    urllib3
    lockfile
    -r{toxinidir}/test_requirements.txt
setenv =
    devtests: DEVELOPER_TESTS=yes
commands =
    pytest tests/

